[websocket]
speech_super_base_url = "wss://speech-eval.aimarketplace.co/api/speech-evaluation/"
tts_base_url = "wss://speech-eval.aimarketplace.co/api/text-to-speech/"
authorization_key = "Api-Key 31c4b5dd307b6fadc8cd5043fb82d984"